<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-StreamKeeper.Recorder-17ecb3a6-a017-4635-93c9-170d2d2078ad</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="dotenv.net" Version="4.2.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
</Project>
